### ISSUE TITLE
Git gutters disappear when theme is on

### ISSUE THREAD

**Issue by kevincoleman** [altcoda/cybervision-vs-code#1]
Love this theme! Not as usable as default themes with the git gutters missing.

I’ll be looking for a local override/fix, and will revisit this issue with a suggestion or PR if there’s a good way to fix it.

**Comment by kevincoleman** [comment]
This can be fixed with a local override. Not sure if the author wants to include something similar in the theme.

Add this to settings.json under `"workbench.colorCustomizations"`

       // Gutter indicators (left)
       "editorGutter.modifiedBackground": "#fff",
       "editorGutter.addedBackground": "#0ff",
       "editorGutter.deletedBackground": "#ff00c8",

       // Scrollbar indicators (right)
       "editorOverviewRuler.addedForeground": "#0ff",
       "editorOverviewRuler.modifiedForeground": "#fff",
       "editorOverviewRuler.deletedForeground": "#ff00c8",

**Comment by kevincoleman** [comment]
I also added a brighter highlight color so it can be seen on top of the black.

       // Highlight color fix
       "editor.selectionBackground": "#7D28A4",
       "editor.selectionHighlightBackground": "#7D28A4"

**Comment by altcoda** [comment]
> 
> 
> This can be fixed with a local override. Not sure if the author wants to include something similar in the theme.
> 
> Add this to settings.json under `"workbench.colorCustomizations"`
> 
> ```
>    // Gutter indicators (left)
>    "editorGutter.modifiedBackground": "#fff",
>    "editorGutter.addedBackground": "#0ff",
>    "editorGutter.deletedBackground": "#ff00c8",
> 
>    // Scrollbar indicators (right)
>    "editorOverviewRuler.addedForeground": "#0ff",
>    "editorOverviewRuler.modifiedForeground": "#fff",
>    "editorOverviewRuler.deletedForeground": "#ff00c8",
> ```

Thank you for your contribution! 

I fixed those colors in the new version. I also improved the highlight, although I picked another color for that since it was too bright for me personally. You can check out the changes in the new version(1.0.9) with some other improvements. Although you won't see everything without turning off personal customizations.
